# Applying ML models to our new supervised quora dataset
Previously we transformed the quora dataset into supervised dataset by preprocessing the data , now we are going to perform some train and testing on this new dataset so as to understand the accuracy of the new dataset.

In [1]:
#importing the necessary libraries needed
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Reading and loading the dataset
df1= pd.read_csv('C:/AI2/quora_supervised_LDA.csv')
df1.head(5)

question  \
0  What is the step by step guide to invest in sh...   
1  What is the story of Kohinoor (Koh-i-Noor) Dia...   
2  How can I increase the speed of my internet co...   
3  Why am I mentally very lonely? How can I solve...   
4  Which one dissolve in water quikly sugar, salt...   

                                       text_low_case  \
0  what is the step by step guide to invest in sh...   
1  what is the story of kohinoor (koh-i-noor) dia...   
2  how can i increase the speed of my internet co...   
3  why am i mentally very lonely? how can i solve...   
4  which one dissolve in water quikly sugar, salt...   

                                          text_punct  \
0  What is the step by step guide to invest in sh...   
1     What is the story of Kohinoor KohiNoor Diamond   
2  How can I increase the speed of my internet co...   
3   Why am I mentally very lonely How can I solve it   
4  Which one dissolve in water quikly sugar salt ...   

                                           text_stop  \
0     What step step guide invest share market india   
1               What story Kohinoor KohiNoor Diamond   
2  How I increase speed internet connection using...   
3                  Why I mentally lonely How I solve   
4  Which one dissolve water quikly sugar salt met...   

                                          text_token  \
0  ['what', 'step', 'step', 'guide', 'invest', 's...   
1  ['what', 'story', 'kohinoor', 'kohinoor', 'dia...   
2  ['how', 'i', 'increase', 'speed', 'internet', ...   
3  ['why', 'i', 'mentally', 'lonely', 'how', 'i',...   
4  ['which', 'one', 'dissolve', 'water', 'quikly'...   

                                          text_lemma  Topic number  \
0     What step step guide invest share market india             5   
1               What story Kohinoor KohiNoor Diamond             5   
2   How I increase speed internet connection use VPN             9   
3                  Why I mentally lonely How I solve             7   
4  Which one dissolve water quikly sugar salt met...             4   

        Topic desc  
0   economy,nation  
1   economy,nation  
2       technology  
3    Relationships  
4  Fitness, health

In [3]:
#importing train_test_split ffrom scikit learn
from sklearn.model_selection import train_test_split

In [4]:
#first we will split the data into labels and features so here we are taking 
#the column 'text_token 'as the feature  and 'topic desc ' as label

now we will see the count of words in the token_text and Topic desc

In [5]:
df1["text_token"].value_counts()

['how', 'i', 'improve', 'pronunciation', 'english']                                                                                                                        58
['what', 'meaning', 'life']                                                                                                                                                39
['how', 'i', 'speak', 'english', 'fluently']                                                                                                                               37
['what', 'new', 'years', 'resolutions', '2017']                                                                                                                            36
['what', 'purpose', 'life']                                                                                                                                                34
                                                                                                                                  

In [6]:
df1["Topic desc"].value_counts()

entertainment           25706
technology              23587
Relationships           21960
education               21034
Fitness, health         20375
life,feelings           18826
Government,judiciary    18645
human life              17055
Humanities,feelings     16645
economy,nation          16167
Name: Topic desc, dtype: int64

In [7]:
X = df1["text_token"]
y = df1["Topic desc"]

In [8]:
X.head(5)

0    ['what', 'step', 'step', 'guide', 'invest', 's...
1    ['what', 'story', 'kohinoor', 'kohinoor', 'dia...
2    ['how', 'i', 'increase', 'speed', 'internet', ...
3    ['why', 'i', 'mentally', 'lonely', 'how', 'i',...
4    ['which', 'one', 'dissolve', 'water', 'quikly'...
Name: text_token, dtype: object

In [9]:
y.head(5)

0     economy,nation
1     economy,nation
2         technology
3      Relationships
4    Fitness, health
Name: Topic desc, dtype: object

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=1)

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
count_vectorizer = CountVectorizer()

In [13]:
X_train_counts = count_vectorizer.fit_transform(X_train)

In [14]:
X_train_counts

<140000x49077 sparse matrix of type '<class 'numpy.int64'>'
	with 888725 stored elements in Compressed Sparse Row format>

In [15]:
X_train.shape

(140000,)

In [16]:
# Load the tfidfTransformer
from sklearn.feature_extraction.text import TfidfTransformer

# Creating an instance of TfidfTransformer
tfidf_transformer = TfidfTransformer()

# Perform a tf-idf fit transform on the X_train_counts
# sparse matrix. Put the result into X_train_tfidf
X_train_transform = tfidf_transformer.fit_transform(X_train_counts)

# Shape is the same as original count vectorizer
# although it now contains word term frequencies multiplied by the
# inverse document frequency
X_train_transform.shape

(140000, 49077)

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [18]:
tfidf_vectorizer = TfidfVectorizer()

In [19]:
# Complete the vectorizing and fit transform on the original X_train
# dataset
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
# Examine shape of the dataset
X_train_tfidf.shape

(140000, 49077)

# Performing Linear SVC on the train test dataset


In [20]:
from sklearn.svm import LinearSVC

In [21]:
# Contents of X_test
X_test.head()

49673     ['i', '23yrs', 'ca', 'final', 'student', 'clea...
171551    ['demonetization', '500', '1000', 'notes', 'cr...
5506      ['what', 'best', 'way', 'learn', 'everything',...
38370                          ['what', 'system', 'theory']
36930     ['has', 'jimmy', 'swaggart', 'ever', 'grammy',...
Name: text_token, dtype: object

In [22]:
# Creating an instance of the LinearSVC classifier
classifier = LinearSVC()

# Target vector relative to X
classifier.fit(X_train_tfidf, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [23]:
# Transform original test message data to a vector
# No need to fit and transform it
X_test_transform = tfidf_vectorizer.transform(X_test)

# Predict message type from Linear SVC classifier
predictions = classifier.predict(X_test_transform)

In [24]:
# Predictions contains the predicted label data from inputted message test data
predictions.shape

(60000,)

In [25]:
# Showing a confusion matrix of results
from sklearn import metrics
print(metrics.confusion_matrix(y_test, predictions))

[[5266   95   95  126   55   80  111  133   99   73]
 [  95 4716   85  101   83   76   85   91  118   91]
 [ 109  106 4015  140   75  109  124  119  103  143]
 [ 115  101  113 5565   77  102  129  117  144  150]
 [  69   78   72   82 4142   91   92   80   59   88]
 [  76   65   96  144   59 5378  149  110   78  141]
 [ 106   76   93   75   65  122 6904   96  115  149]
 [ 143   99   98  140   71  158  127 3941  142  110]
 [ 128  116   68  189   80   77  118  127 4557   98]
 [  55   63   82  109   60  141  132   84   79 6328]]


In [26]:
# Print a classification report
print(metrics.classification_report(y_test,predictions))

                      precision    recall  f1-score   support

     Fitness, health       0.85      0.86      0.86      6133
Government,judiciary       0.86      0.85      0.85      5541
 Humanities,feelings       0.83      0.80      0.81      5043
       Relationships       0.83      0.84      0.84      6613
      economy,nation       0.87      0.85      0.86      4853
           education       0.85      0.85      0.85      6296
       entertainment       0.87      0.89      0.88      7801
          human life       0.80      0.78      0.79      5029
       life,feelings       0.83      0.82      0.82      5558
          technology       0.86      0.89      0.87      7133

            accuracy                           0.85     60000
           macro avg       0.85      0.84      0.84     60000
        weighted avg       0.85      0.85      0.85     60000



In [27]:
from sklearn.pipeline import Pipeline
text_classifier = Pipeline([('tfidf_vect', TfidfVectorizer()),
                     ('LinearSVC_classifier', LinearSVC()),
])

# Feed the training data through the pipeline
text_classifier.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf_vect',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('LinearSVC_classifier',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scal

In [28]:
predictions = text_classifier.predict(X_test)

In [29]:
print(metrics.confusion_matrix(y_test,predictions))


[[5266   95   95  126   55   80  111  133   99   73]
 [  95 4716   85  101   83   76   85   91  118   91]
 [ 109  106 4015  140   75  109  124  119  103  143]
 [ 115  101  113 5565   77  102  129  117  144  150]
 [  69   78   72   82 4142   91   92   80   59   88]
 [  76   65   96  144   59 5378  149  110   78  141]
 [ 106   76   93   75   65  122 6904   96  115  149]
 [ 143   99   98  140   71  158  127 3941  142  110]
 [ 128  116   68  189   80   77  118  127 4557   98]
 [  55   63   82  109   60  141  132   84   79 6328]]


In [30]:
# Print a classification report
print(metrics.classification_report(y_test,predictions))

                      precision    recall  f1-score   support

     Fitness, health       0.85      0.86      0.86      6133
Government,judiciary       0.86      0.85      0.85      5541
 Humanities,feelings       0.83      0.80      0.81      5043
       Relationships       0.83      0.84      0.84      6613
      economy,nation       0.87      0.85      0.86      4853
           education       0.85      0.85      0.85      6296
       entertainment       0.87      0.89      0.88      7801
          human life       0.80      0.78      0.79      5029
       life,feelings       0.83      0.82      0.82      5558
          technology       0.86      0.89      0.87      7133

            accuracy                           0.85     60000
           macro avg       0.85      0.84      0.84     60000
        weighted avg       0.85      0.85      0.85     60000



In [31]:
print(metrics.accuracy_score(y_test,predictions))

0.8468666666666667


As we can see the Linear SVC model gives the accuracy of 84% and it is the highest accuracy amongst all the models i trained so i have taken 10 random questions from the dataset provided and predicted its group.

In [35]:
#Q1 
text_classifier.predict(["What is the step by step guide to invest in share market in india?"])

array(['economy,nation'], dtype=object)

In [36]:
#Q2
text_classifier.predict(["How can I increase the speed of my internet connection while using a VPN?"])

array(['technology'], dtype=object)

In [37]:
#Q3
text_classifier.predict(["Astrology: I am a Capricorn Sun Cap moon and cap rising...what does that say about me?"])

array(['life,feelings'], dtype=object)

In [38]:
#Q4
text_classifier.predict(["What was your first sexual experience like?"])

array(['human life'], dtype=object)

In [42]:
#Q5
text_classifier.predict(["What are the questions should not ask on Quora?"])

array(['technology'], dtype=object)

In [45]:
#Q6
text_classifier.predict(["What is web application?"])

array(['technology'], dtype=object)

In [46]:
#Q7
text_classifier.predict(["What Game of Thrones villain would be the most likely to give you mercy?"])

array(['life,feelings'], dtype=object)

In [47]:
#Q8
text_classifier.predict(["Why do some people think Obama will try to take their guns away?"])

array(['Government,judiciary'], dtype=object)

In [48]:
#Q9
text_classifier.predict(["When can I expect my Cognizant confirmation mail?"])

array(['technology'], dtype=object)

In [49]:
#Q10
text_classifier.predict(["Nd she is always sad?"])

array(['life,feelings'], dtype=object)

# Building NAive bayes

In [50]:
from sklearn.naive_bayes import MultinomialNB

In [51]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
text_classifier = Pipeline([('tfidf_vect', TfidfVectorizer()),
                     ('M_NB ', MultinomialNB()),
])

# Feed the training data through the pipeline
text_classifier.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf_vect',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('M_NB ',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [52]:
predictions = text_classifier.predict(X_test)


In [53]:
print(metrics.confusion_matrix(y_test,predictions))

[[4988   81   39  240   49  119  279   83   79  176]
 [ 196 4349   35  195   66  131  227   60  134  148]
 [ 222  186 2635  415   60  369  464   99  164  429]
 [ 152  119   33 5335   48  168  309   46  123  280]
 [  98  181   38  167 3381  219  338   52   84  295]
 [ 127   62   26  343   16 4873  245   35  102  467]
 [ 144   38   20  113   24  164 6924   33   86  255]
 [ 315  121   52  354   63  426  398 2759  203  338]
 [ 244  157   39  384   62  127  318   66 3963  198]
 [  60   74   13  209   36  162  266   31   66 6216]]


In [54]:
print(metrics.classification_report(y_test,predictions))

                      precision    recall  f1-score   support

     Fitness, health       0.76      0.81      0.79      6133
Government,judiciary       0.81      0.78      0.80      5541
 Humanities,feelings       0.90      0.52      0.66      5043
       Relationships       0.69      0.81      0.74      6613
      economy,nation       0.89      0.70      0.78      4853
           education       0.72      0.77      0.75      6296
       entertainment       0.71      0.89      0.79      7801
          human life       0.85      0.55      0.67      5029
       life,feelings       0.79      0.71      0.75      5558
          technology       0.71      0.87      0.78      7133

            accuracy                           0.76     60000
           macro avg       0.78      0.74      0.75     60000
        weighted avg       0.77      0.76      0.75     60000



In [55]:
print(metrics.accuracy_score(y_test,predictions))

0.75705


In [56]:
from sklearn.ensemble import RandomForestClassifier

In [57]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
text_classifier = Pipeline([('tfidf_vect', TfidfVectorizer()),
                     ('Random_FC ', RandomForestClassifier()),
])

# Feed the training data through the pipeline
text_classifier.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf_vect',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_patt...
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None

In [119]:
predictions = text_classifier.predict(X_test)

In [120]:
print(metrics.confusion_matrix(y_test,predictions))

[[4392  132  271  278  101  132  235  227  199  166]
 [ 231 3921  200  214  162  126  174  206  190  117]
 [ 222  164 3348  218  110  198  237  162  156  228]
 [ 238  152  255 4741  106  184  265  197  237  238]
 [ 126  157  206  127 3581  132  158  114  102  150]
 [ 158   86  178  263  105 4582  302  200  135  287]
 [ 183   95  200  149  108  149 6399  139  168  211]
 [ 283  179  272  304  142  251  239 2926  233  200]
 [ 265  174  262  308  120  116  252  222 3711  128]
 [ 126   88  178  217  102  165  283  137  108 5729]]


In [121]:
print(metrics.classification_report(y_test,predictions))

                      precision    recall  f1-score   support

     Fitness, health       0.71      0.72      0.71      6133
Government,judiciary       0.76      0.71      0.73      5541
 Humanities,feelings       0.62      0.66      0.64      5043
       Relationships       0.70      0.72      0.71      6613
      economy,nation       0.77      0.74      0.75      4853
           education       0.76      0.73      0.74      6296
       entertainment       0.75      0.82      0.78      7801
          human life       0.65      0.58      0.61      5029
       life,feelings       0.71      0.67      0.69      5558
          technology       0.77      0.80      0.79      7133

            accuracy                           0.72     60000
           macro avg       0.72      0.71      0.72     60000
        weighted avg       0.72      0.72      0.72     60000



In [122]:
print(metrics.accuracy_score(y_test,predictions))

0.7221666666666666
